version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0
jobs:
  build:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Running Tests and Generating Coverage Report
          command: coverage run -m unittest && coverage report -m && coverage xml
      - run:
          name: Create sonar-project.properties
          command: |
            echo "sonar.organization=${SONAR_ORGANIZATION}" > sonar-project.properties
            echo "sonar.projectKey=${SONAR_PROJECT_KEY}" >> sonar-project.properties
            echo "sonar.python.coverage.reportPaths=coverage.xml" >> sonar-project.properties
            echo "sonar.sources=main.py" >> sonar-project.properties
            echo "sonar.tests=test.py" >> sonar-project.properties
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build