version: 2.1

# 1. Declara el Orb de Code Climate
orbs:
  codeclimate: codeclimate/codeclimate@1.0.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.1 # Tu imagen de Docker es correcta
    steps:
      - checkout

      # 2. Instala el binario de forma automática
      - codeclimate/install

      - run:
          name: Instalar dependencias
          command: pip install -r requirements.txt
      
      # 3. Notifica a Quality que el build comienza
      - run:
          name: Setup Quality Reporter
          command: cc-test-reporter before-build

      # 4. Ejecuta las pruebas y genera el reporte XML
      - run:
          name: Ejecutar pruebas y generar cobertura
          command: |
            coverage run -m unittest
            coverage xml -o coverage.xml # Genera el archivo coverage.xml

      # 5. Sube el reporte de cobertura (¡Paso clave corregido!)
      #    - Se ejecuta siempre para reportar también los fallos.
      #    - Le dice a Quality dónde está y qué tipo de archivo es.
      - run:
          name: Subir reporte a Quality
          command: cc-test-reporter after-build --exit-code $? --coverage-input-type cobertura coverage.xml
          when: always
workflows:
  build-workflow:
    jobs:
      - build