version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0
jobs:
  build:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Running Tests and Generating Coverage Report
          command: coverage run -m unittest && coverage xml
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build